#!/bin/bash
#rwfilter --dport=5005 --pass=stdout ext2ext-S0_20170726.* | rwcut --fields=sIP,dIP,dPort,sTime,duration,etime

if [ $# = 0 ]; then
  echo "List all flows to the special destination port."
  echo "parameters: MM DD"
  exit
else
  mm=$1
  dd=$2
  year="2017"
  rwfilter --dport=5005 --pass=stdout /data/ext2ext/$year/$mm/$dd/* | rwcut --fields=sIP,dIP,sTime,etime

#ext2ext-S0_20170727.* | rwcut --fields=sIP,dIP,sTime,etime
fi
