#!/bin/bash

send_pcap () {
  local file=$1

  local pcap=$file.pcap
  cp $file $pcap
  bzip2 $pcap
  local zipped=$pcap.bz2
  scp -i gate.pem $zipped ctrl.chgate.net:pcaps/
  rm $zipped
}

send_pcap $1

